### ISSUE TITLE
IOS build failed 

### ISSUE THREAD

**Issue by ramisalem** [mateioprea/react-native-intercom#4] opened 2020-10-23 07:22 UTC
Hello, 
I am getting the following issue in the AppDelegate file, I have installed the package  with blew  steps 
1) yarn add react-native-intercom-native 
2) npx intercom-link 

![Screen Shot 1442-03-06 at 12 49 57 PM](https://user-images.githubusercontent.com/25037017/96968206-44b00f80-152e-11eb-80b2-0265460b590a.png)

![Screen Shot 1442-03-06 at 12 54 12 PM](https://user-images.githubusercontent.com/25037017/96968614-dc156280-152e-11eb-9cf3-e43affe5bc36.png)

Thanks in advance

**Comment by mateioprea** [comment] 2020-10-23 07:33
Hi @ramisalem, you have a ```;``` before each curly bracket. Just remove it and everything should work.
Meaning that you should remove the ; after the ```deviceToken``` and after the ```completionHandler```

Curious how those ended there.

**Comment by ramisalem** [comment] 2020-10-23 08:23
Thanks for the response, here is what I got after removing ; 

![Screen Shot 1442-03-06 at 1 51 25 PM](https://user-images.githubusercontent.com/25037017/96974432-da4f9d00-1536-11eb-8d3f-3724cedab718.png)
![Screen Shot 1442-03-06 at 1 51 48 PM](https://user-images.githubusercontent.com/25037017/96974469-e89db900-1536-11eb-9b20-f00c9f159752.png)

**Comment by mateioprea** [comment] 2020-10-23 09:05
I'll add a fix for this, i know what the problem is. 

Can you take those tho methods ```didRegisterForRemoteNotificationsWithDeviceTOken``` and ```didReceiveRemoteNotification``` and add them add the end of your AppDelegate.m, before the last @end ? 

Something like this: https://www.dropbox.com/s/anaej30s6ycjr99/Screenshot%202020-10-23%20at%2012.04.48.png?dl=0

**Comment by ramisalem** [comment] 2020-10-23 11:53
Hi, now it the issue is resloved, Thank you very much

**Closed** 2020-10-28 18:34 UTC
